# Generated by Django 5.2.6 on 2025-09-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=3, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(related_name='products', to='apptextio.sizevariant'),
        ),
    ]
