# Generated by Django 5.2.6 on 2025-09-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0002_sizevariant_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='des_price',
            new_name='dis_price',
        ),
    ]
