# Generated by Django 5.2.6 on 2025-09-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0003_rename_des_price_product_dis_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='products', to='apptextio.sizevariant'),
        ),
    ]
