# Generated by Django 5.2.6 on 2025-09-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0005_coupon_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizevariant',
            name='size',
            field=models.CharField(choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('Extra Large', 'XL')], max_length=12, unique=True),
        ),
    ]
