# Generated by Django 5.2.6 on 2025-09-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0007_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Purnea', 'Purnea'), ('Madhepura', 'Madhepura'), ('Katihar', 'Katihar'), ('Bhagelpur', 'Bhagelpur'), ('Patna', 'Patna')], max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Up', 'Up'), ('Jharkhand', 'Jharkhand'), ('Punjab', 'Punjab'), ('Haryana', 'Haryana')], max_length=200),
        ),
    ]
