# Generated by Django 5.2.6 on 2025-09-15 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0008_alter_address_city_alter_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apptextio.address'),
        ),
    ]
