# Generated by Django 5.2.6 on 2025-09-16 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0009_order_address_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_id',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apptextio.order'),
        ),
    ]
