# Generated by Django 5.2.6 on 2025-09-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0010_rename_address_id_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='apptextio.orderitem'),
        ),
    ]
