# Generated by Django 5.2.6 on 2025-09-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0011_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
