# Generated by Django 5.2.6 on 2025-09-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0012_order_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_buynow',
            field=models.BooleanField(default=False),
        ),
    ]
