# Generated by Django 5.2.6 on 2025-09-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0013_order_is_buynow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_buynow',
        ),
    ]
