# Generated by Django 5.2.6 on 2025-09-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0014_remove_order_is_buynow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='alt_contact',
            field=models.CharField(max_length=10),
        ),
    ]
