# Generated by Django 5.2.6 on 2025-09-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0017_rename_razorpay_payment_id_order_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
