# Generated by Django 5.2.6 on 2025-09-24 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0018_order_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_paid',
            new_name='from_buynow',
        ),
    ]
