# Generated by Django 5.2.6 on 2025-10-13 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0020_remove_order_items_alter_orderitem_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apptextio.orderitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='from_buynow',
            field=models.BooleanField(default=False),
        ),
    ]
