# Generated by Django 5.2.6 on 2025-10-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0021_order_products_order_total_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_product_price',
            new_name='price_at_order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_product_price',
            new_name='product_dis_price_at_order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_price_at_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
