# Generated by Django 5.2.6 on 2025-10-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0022_rename_total_product_price_order_price_at_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
