# Generated by Django 5.2.6 on 2025-10-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0025_alter_completeorder_city_alter_completeorder_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeorder',
            name='payable_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='completeorder',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='completeorderitem',
            name='product_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='completeorderitem',
            name='product_img',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='completeorderitem',
            name='product_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
