# Generated by Django 5.2.6 on 2025-10-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0026_completeorder_payable_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='completeorderitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.DeleteModel(
            name='CompleteOrder',
        ),
        migrations.DeleteModel(
            name='CompleteOrderItem',
        ),
    ]
