# Generated by Django 5.2.6 on 2025-10-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0028_completeorder_completeorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeorder',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, default='It didn`t work', max_length=100),
        ),
    ]
