# Generated by Django 5.2.6 on 2025-10-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0029_completeorder_razor_pay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeorder',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='completeorder',
            name='razor_pay_order_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
