# Generated by Django 5.2.6 on 2025-10-16 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0030_completeorder_create_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price_at_order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_dis_price_at_order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_price_at_order',
        ),
    ]
