# Generated by Django 5.2.6 on 2025-10-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0033_orderitem_temp_user_alter_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
