# Generated by Django 5.2.6 on 2025-10-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0034_remove_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeorderitem',
            name='user',
        ),
    ]
