# Generated by Django 5.2.6 on 2025-10-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0036_variant_delete_size_rename_coupon_id_order_coupon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
