# Generated by Django 5.2.6 on 2025-10-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0037_rename_product_id_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='alt_contact',
            new_name='contact',
        ),
    ]
