# Generated by Django 5.2.6 on 2025-10-26 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0038_rename_alt_contact_address_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='variant_product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='temp_user',
        ),
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='apptextio.product'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='apptextio.sizevariant'),
        ),
    ]
