# Generated by Django 5.2.6 on 2025-10-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0039_rename_product_orderitem_variant_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.ImageField(default='img', upload_to='photo/'),
        ),
    ]
