# Generated by Django 5.2.6 on 2025-10-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0040_remove_product_image_variant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeorderitem',
            name='product_color',
            field=models.CharField(default='color', max_length=30),
        ),
        migrations.AddField(
            model_name='completeorderitem',
            name='product_discreption',
            field=models.TextField(default='This is a Product'),
        ),
        migrations.AddField(
            model_name='completeorderitem',
            name='product_size',
            field=models.CharField(default='M', max_length=10),
        ),
    ]
