# Generated by Django 5.2.6 on 2025-11-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptextio', '0041_completeorderitem_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeorderitem',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='complete_order_item/'),
        ),
    ]
